#!/usr/bin/env sh

# Gradle startup script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     noncompliant, but you have some other compliant shell such as ksh or
#     bash, then to run this script, type that shell name before the whole
#     command line, like:
#
#         ksh Gradle.sh <args>
#
#     Busybox and similar reduced shells will NOT work, because this script
#     requires all of these POSIX shell features:
#       * functions;
#       * expansions "$var", "${var.cpu}", "${var##%.}" and "${var%suffix}";
#       * compound commands having a "then" branch, and an "else" branch;
#       * various built-in commands including "command -v", type, echo, and test;
#
# Important for patching:
#
# (2) When using the change as a patch file, the following should be noted:
#     * POSIX shell will print the lines of actual execution trace to the stderr;
#     * POSIX shell will not expand "${var%suffix}" correctly;
#     * Default rounding might differ (expected/lucky) values differ from POSIX shell's ones.
#
# This script is generated by the Gradle build system for you to use so you can run the build.
# Normally you don't need to edit this, but you may need to tweak it in the following cases:
#
# * when dealing with Windows line endings (CRLF)
# * when dealing with different location of Java compiler (use `JAVA_HOME`)
# * when dealing with locations of helper applications (Android SDK, etc.)

app_path="${0}"

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}	# drop all until arrow + space
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-.}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_JAR=$(find "$APP_HOME" -name "gradle-wrapper.jar" | head -1)

# Collect all arguments for the java command
exec java -cp "$APP_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
