package com.tools.maestro.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF5B5FEF)
val md_theme_light_onPrimary = Color.White
val md_theme_light_primaryContainer = Color(0xFFE5E6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF17174A)
val md_theme_light_secondary = Color(0xFF596070)
val md_theme_light_onSecondary = Color.White
val md_theme_light_secondaryContainer = Color(0xFFE0E2F0)
val md_theme_light_onSecondaryContainer = Color(0xFF171A24)
val md_theme_light_tertiary = Color(0xFF76546D)
val md_theme_light_onTertiary = Color.White
val md_theme_light_tertiaryContainer = Color(0xFFFFD8F0)
val md_theme_light_onTertiaryContainer = Color(0xFF2C1227)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color.White
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8F8FC)
val md_theme_light_onBackground = Color(0xFF1A1A20)
val md_theme_light_surface = Color(0xFFF8F8FC)
val md_theme_light_onSurface = Color(0xFF1A1A20)
val md_theme_light_surfaceVariant = Color(0xFFE3E3EC)
val md_theme_light_onSurfaceVariant = Color(0xFF46464F)
val md_theme_light_outline = Color(0xFF777780)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F7)
val md_theme_light_inverseSurface = Color(0xFF2F3036)
val md_theme_light_inversePrimary = Color(0xFFC4C5FF)

val md_theme_dark_primary = Color(0xFFC4C5FF)
val md_theme_dark_onPrimary = Color(0xFF292B78)
val md_theme_dark_primaryContainer = Color(0xFF4143A4)
val md_theme_dark_onPrimaryContainer = Color(0xFFE5E6FF)
val md_theme_dark_secondary = Color(0xFFC3C5D5)
val md_theme_dark_onSecondary = Color(0xFF2C2F39)
val md_theme_dark_secondaryContainer = Color(0xFF424650)
val md_theme_dark_onSecondaryContainer = Color(0xFFE0E2F0)
val md_theme_dark_tertiary = Color(0xFFE5BAD7)
val md_theme_dark_onTertiary = Color(0xFF43263D)
val md_theme_dark_tertiaryContainer = Color(0xFF5C3C55)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8F0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0D0E12)
val md_theme_dark_onBackground = Color(0xFFE5E1E8)
val md_theme_dark_surface = Color(0xFF111217)
val md_theme_dark_onSurface = Color(0xFFE5E1E8)
val md_theme_dark_surfaceVariant = Color(0xFF202127)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC0CA)
val md_theme_dark_outline = Color(0xFF8A8B94)
val md_theme_dark_inverseOnSurface = Color(0xFF29282E)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E8)
val md_theme_dark_inversePrimary = Color(0xFF5B5FEF)

val SuccessGreen = Color(0xFF57D38C)
val WarningOrange = Color(0xFFFFB74D)
val ErrorRed = Color(0xFFFF6B6B)
val InfoBlue = Color(0xFF64B5F6)
